1.2.Software Technologies/11.C#Lab/02.ToDoList/02.ToDoList/Models/Task.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace _02.ToDoList.Models
{
    public class Task
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }
    }
}

1.2.Software Technologies/11.C#Lab/02.ToDoList/02.ToDoList/Models/TaskDbContext.cs
namespace _02.ToDoList.Models
{
    using System;
    using System.Data.Entity;
    using System.Linq;

    public class TaskDbContext : DbContext
    {
        public TaskDbContext()
            : base("name=TaskDbContext")
        {
        }
    
       
        public virtual DbSet<Task> Tasks { get; set; }
    }

    //public class MyEntity
    //{
    //    public int Id { get; set; }
    //    public string Name { get; set; }
    //}
}

1.2.Software Technologies/11.C#Lab/02.ToDoList/02.ToDoList/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _02.ToDoList.Models;

namespace _02.ToDoList.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            using (var db = new TaskDbContext())
            {
                var tasks = db.Tasks.ToList();

                return View(tasks);
            }
        }
    }
}

1.2.Software Technologies/11.C#Lab/02.ToDoList/02.ToDoList/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _02.ToDoList.Models;

namespace _02.ToDoList.Controllers
{
    public class TaskController : Controller
    {
        [HttpPost]
        public ActionResult Create(Task task)
        {
            if (task == null)
            {
                return RedirectToAction("Index", "Home");
            }

            using (var db = new TaskDbContext())
            {
                db.Tasks.Add(task);
                db.SaveChanges();
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            using (var db = new TaskDbContext())
            {
                var task = db.Tasks.Find(id);

                if (task == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                db.Tasks.Remove(task);
                db.SaveChanges();
            }

            return RedirectToAction("Index", "Home");

        }

        
    }
}

1.2.Software Technologies/11.C#Lab/02.ToDoList/02.ToDoList/Views/Home/Index.cshtml
@model List<_02.ToDoList.Models.Task>
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        <h3>TODO List</h3>
        <ol>
            @foreach (var task in Model)
            {
                <li>@task.Title @Html.ActionLink("[Delete]", "Delete", "Task", htmlAttributes: null, routeValues: new { id = task.Id })</li>
            }
        </ol>
        @using (Html.BeginForm("Create", "Task", null, FormMethod.Post, new { @class = "form-inline" }))
        {
            <div class="form-group">
                <input type="text" class="form-control" name="title" placeholder="Task Title" autofocus="autofocus" />
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Add Task" />
            </div>
        }
    </div>
</div>